### ISSUE TITLE
Clean tabulate.py

### ISSUE THREAD

**Issue by epogrebnyak** [epogrebnyak/rosstat-kep-data#107]
refactor coe for pure_tabulate(iter, header=TABLE_HEADER) and do not use itertools, if possible or document its use better

**Comment by epogrebnyak** [comment]
https://github.com/epogrebnyak/rosstat-kep-data/blob/master/kep/common/tabulate.py

**Comment by sinancetinkaya** [comment]
def pure_tabulate(iter, header=TABLE_HEADER):
    """Returns markdown-formatted table as a string."""
    # Calculate column widths
    table = list(iter)
    widths = get_max_widths(itertools.chain([header], table))
    # | Text      | Another text |
    template =              '| ' + ' | '.join(cell_format(x) for x in widths) + ' |'
    #                        |:------|:------------------------------------|
    header_separator_line = '|:' + '-|:'.join('-' * x for x in widths) + '-|'
    # Format and combine all rows into table

    rows = [template.format(*header), header_separator_line]
    column_count = len(widths)
    for row in table:
        if column_count > len(row):
            col = column_count - len(row)
            row += [''] * col
        rows.extend((template.format(*row), header_separator_line))

    return '\n'.join(rows)

**Comment by epogrebnyak** [comment]
Closed by 46cafef8484329b3dde62de87702457cf11af2f0
