### ISSUE TITLE
Write doctests for split*() functions 

### ISSUE THREAD

**Issue by epogrebnyak** [epogrebnyak/rosstat-kep-data#139]
Marked as TODO at <https://github.com/epogrebnyak/data-rosstat-kep/blob/kep2/kep2/datapoints.py#L156-L211>

**Comment by rohlin17** [comment]
332dbd9eb2bc03454f3b30707bbf99c32f9a3908

**Comment by rohlin17** [comment]
Replaced generated strings with real from tab.csv ef4eaf5d491fed5eaf54bc84b1199a42e7f95af4

**Comment by epogrebnyak** [comment]
Merged to kep2 branch.
