### ISSUE TITLE
Database operations not performed in one session, require console reset. 

### ISSUE THREAD

**Issue by epogrebnyak** [epogrebnyak/rosstat-kep-data#43]
As described in https://github.com/epogrebnyak/rosstat-kep-data/blob/master/src/errors/error_no_wipe.py

**Comment by vrastonero** [comment]
Sqlite is OK : 'wipe' and 'import_csv' work as they should.The problem was with cached result of database.read_dfs call. So it is reasonable to clear cache when database is changes.

**Comment by epogrebnyak** [comment]
Agreed, but better leave closing the issue to whoever opened it.
