### ISSUE TITLE
Testing: finish test test_mwe.py

### ISSUE THREAD

**Issue by epogrebnyak** [epogrebnyak/rosstat-kep-data#57]
As descibed in todos in https://github.com/epogrebnyak/rosstat-kep-data/blob/master/kep/test/test_mwe.py

**Comment by alexanderlukanin13** [comment]
@epogrebnyak In master, `test_mwe` fails because new column `PROD_yoy` is added to annual table. Is it correct? Should I modify the test?

**Comment by epogrebnyak** [comment]
@alexanderlukanin13: `test_mwe` passes when it is run stand-alone, but fails is a package when many tests are run. The test is good as it is, I cannot see where extra variable `PROD_yoy` is coming from: in https://github.com/epogrebnyak/rosstat-kep-data/blob/master/kep/test/test_mwe.py#L88 we clean the database. Maybe some cached copy is used in a test, this should be fixed, please give your suggestions.

**Comment by alexanderlukanin13** [comment]
@epogrebnyak I investigated sqlite3, pandas and pytest... but finally I saw this: https://github.com/epogrebnyak/rosstat-kep-data/blob/8b73384c49a93b016eaf863d1f4ea3c6582a0e31/kep/database/db.py#L64

**Comment by epogrebnyak** [comment]
... "I saw this"  is not a suggestion, what to do next about it? Best if you tried replicating the tests with cache or without it. Does `py.test` have errors on your machine?

**Comment by epogrebnyak** [comment]
I have the test working both stand-alone and (when caching is disabled) - in package. 

Note: later may try different import functions for testing and production.
