### ISSUE TITLE
example_import.py contains duplicate lines

### ISSUE THREAD

**Issue by dniku** [epogrebnyak/rosstat-kep-data#85]
Is this intentional?

Also, it may be a good idea to comment out the last line, since it replicates what all previous lines do anyway.

**Comment by dniku** [comment]
Please have another look at this: for example, `write_plots` is still called twice.

**Comment by epogrebnyak** [comment]
Fixed by 878104d637c0c9ac0299e148b77858cc58346ca8.  Many thanks for pointing out - I was long wondering why writing pngs takes so long...  

TODO (EP): add more print() statements.

OK to close now?

**Comment by dniku** [comment]
@epogrebnyak Still `db_dump` is called twice.

**Comment by epogrebnyak** [comment]
@Pastafarianist: can you close now?
